/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package infocollector;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mattis
 */
public class DishGUI extends javax.swing.JFrame {
    
    // info boxes strings
    private String exampleDishInfoEntered = "For Example: \nPotatismos\n\nGjord på potatis\n\n35 kr";
    private String exampleDishInfoUnEntered = "The Dish Name\n(One blank line)\nThe description of the dish\n(One blank line)\nPrice for dish";
    private String dishTypeFocusGained = "";
    private String dishTypeFocusLost = "Dish Type";
    private String dishInfoFocusGained = "";
    private String dishInfoFocusLost = "Dish name\n\nDish description\n\nDish price";
    
    // file prefixes
    private String restaurantNamePre = "@restaurantName: ";
    private String restaurantLocationPre = "@restaurantLocation: ";
    private String dishTypePre = "@dishType: ";
    private String dishNamepre = "@dishName: ";
    private String dishDescriptionPre = "@dishDescription: ";
    private String dishPricePre = "@dishPrice: ";
    private String signalEOF = "@EOF";
    
    public static String folderName = "MATFolder";
    public static String fileExtensionName = "MAT";
    
    private RestaurantInfo restInfo;
    /**
     * Creates new form TestGUI
     * TODO: add in the constructor so the file handler gets sent to the constructor, or maybe
     * just add so an object gets sent with and this object should be composed of the information
     * necessary for the file........
     */
    public DishGUI(RestaurantInfo temp) {
        initComponents();
        this.restInfo = temp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoPanel = new javax.swing.JPanel();
        enterDishType = new javax.swing.JLabel();
        dishType = new javax.swing.JTextField();
        enterDishInfo = new javax.swing.JLabel();
        infoScrPn = new javax.swing.JScrollPane();
        dishInfo = new javax.swing.JTextArea();
        doneBtn = new javax.swing.JButton();
        exampleScrPn = new javax.swing.JScrollPane();
        exampleDishInfo = new javax.swing.JTextArea();
        titel = new javax.swing.JLabel();
        ContinueBtn = new javax.swing.JLabel();
        inputError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                askSave(evt);
            }
        });

        enterDishType.setText("Enter Dish Type Here:");

        dishType.setText("Dish Type");
        dishType.setToolTipText("Eg. Förrätt");
        dishType.setName("DishType");
        dishType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishTypeActionPerformed(evt);
            }
        });
        dishType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dishTypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dishTypeFocusLost(evt);
            }
        });

        enterDishInfo.setText("Enter Dish Info Here:");

        dishInfo.setColumns(20);
        dishInfo.setLineWrap(true);
        dishInfo.setRows(5);
        dishInfo.setText("Dish name\n\nDish description\n\nDish price");
        dishInfo.setToolTipText("Eg. Name of Dish");
        dishInfo.setName("DishInfo");
        dishInfo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dishInfoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dishInfoFocusLost(evt);
            }
        });
        infoScrPn.setViewportView(dishInfo);

        doneBtn.setText("Done");
        doneBtn.setName("DoneBtn");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        exampleDishInfo.setColumns(5);
        exampleDishInfo.setEditable(false);
        exampleDishInfo.setLineWrap(true);
        exampleDishInfo.setRows(5);
        exampleDishInfo.setText("The Dish Name\n(One blank line)\nThe description of the dish\n(One blank line)\nPrice for dish");
        exampleDishInfo.setToolTipText("for example:\nPotatismos\n\nGjort på potatis\n\n35 kr"); // NOI18N
        exampleDishInfo.setName("exampleArea");
        exampleDishInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exampleDishInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exampleDishInfoMouseExited(evt);
            }
        });
        exampleScrPn.setViewportView(exampleDishInfo);

        titel.setFont(new java.awt.Font("Buxton Sketch", 3, 36)); // NOI18N
        titel.setText("Dish Editor");

        ContinueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secretProject/rightArrowTransparent.gif"))); // NOI18N
        ContinueBtn.setName("ContinueArrow");
        ContinueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContinueBtnMouseClicked(evt);
            }
        });

        inputError.setFocusable(false);

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterDishType)
                            .addComponent(enterDishInfo))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                        .addComponent(exampleScrPn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titel)
                    .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(infoScrPn, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                        .addComponent(dishType))
                    .addComponent(inputError))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(doneBtn))
                    .addComponent(ContinueBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titel)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enterDishType)
                            .addComponent(dishType))
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(enterDishInfo)
                                .addGap(26, 26, 26)
                                .addComponent(exampleScrPn))
                            .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(infoScrPn, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(inputError)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContinueBtn)
                        .addGap(160, 160, 160)
                        .addComponent(doneBtn)
                        .addGap(36, 36, 36))))
        );

        doneBtn.getAccessibleContext().setAccessibleName("DoneBtn");
        ContinueBtn.getAccessibleContext().setAccessibleName("ContinueArrow");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dishTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dishTypeActionPerformed

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        // TODO add your handling code here: save and quit, save = create file
        System.out.println("saving and quiting");
        
        // has to check so the entered info is correct for the last one aswell before exiting
        String temp = inputCheck();
        if(!temp.equals("")){
            inputError.setText(temp);
            return;
        } else{
            // save input and continue
            DishInfo dishToAdd = new DishInfo(dishType.getText()); // creates a DishInfo object with the dishType set
            addDishInfo(dishToAdd); // adds all the individual dishes to dishToAdd
            restInfo.addDishInfo(dishToAdd); // adds dishToAdd to restInfo
        }
        
        // creates directory if it does not already exist
        File checkDir = new File(folderName);
        if(checkDir.mkdir()){
            System.out.println("made directory");
        }
        
        ObjectFileIO fileOutput = new ObjectFileIO(this.getFileName());
        fileOutput.saveFiles(restInfo);
        
        /*
        PrintWriter outFile;
        try {
            // create file and save info in file
            outFile = new PrintWriter(this.getFileName());
        } catch (FileNotFoundException ex) {
            System.out.println("could not create file");
            return;
        }
        outFile.println(restaurantNamePre + restInfo.getRestaurantName());
        outFile.println(restaurantLocationPre + restInfo.getLocation());
        
        outFile.println();
        
        writeDishInfosToFile(outFile);
        
        outFile.print(signalEOF);
        outFile.close();
        /**/
        
        this.dispose();
    }//GEN-LAST:event_doneBtnActionPerformed

    private void exampleDishInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exampleDishInfoMouseEntered
        // TODO add your handling code here:
        exampleDishInfo.setText(exampleDishInfoEntered);
    }//GEN-LAST:event_exampleDishInfoMouseEntered

    private void exampleDishInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exampleDishInfoMouseExited
        // TODO add your handling code here:
        exampleDishInfo.setText(exampleDishInfoUnEntered);
    }//GEN-LAST:event_exampleDishInfoMouseExited

    private void dishTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dishTypeFocusGained
        // TODO add your handling code here:
        String temp = dishType.getText();
        if(temp.equals(dishTypeFocusLost)){
            dishType.setText(dishTypeFocusGained);
        }
        
    }//GEN-LAST:event_dishTypeFocusGained

    private void dishTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dishTypeFocusLost
        // TODO add your handling code here:
        String temp = dishType.getText();
        if(temp.equals(dishTypeFocusGained)){
            dishType.setText(dishTypeFocusLost);
        }
    }//GEN-LAST:event_dishTypeFocusLost

    private void dishInfoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dishInfoFocusGained
        // TODO add your handling code here:
        String temp = dishInfo.getText();
        if(temp.equals(dishInfoFocusLost)){
            dishInfo.setText(dishInfoFocusGained);
        }
    }//GEN-LAST:event_dishInfoFocusGained

    private void dishInfoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dishInfoFocusLost
        // TODO add your handling code here:
        String temp = dishInfo.getText();
        if(temp.equals(dishInfoFocusGained)){
            dishInfo.setText(dishInfoFocusLost);
        }
    }//GEN-LAST:event_dishInfoFocusLost

    private void ContinueBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueBtnMouseClicked
        // TODO add your handling code here:
        /*
         * check if all input ok
         * save input = add info to the restInfo object
         * open another Dishinput ui
         * dispose of this window
         */
        String temp = inputCheck();
        if(!temp.equals("")){
            inputError.setText(temp);
            return;
        } else{
            // save input and continue
            DishInfo dishToAdd = new DishInfo(dishType.getText());
            addDishInfo(dishToAdd); // adds all the individual dishes to dishToAdd
            restInfo.addDishInfo(dishToAdd); // adds dishToAdd to restInfo
            System.out.println("add save input and continue");
            new DishGUI(restInfo).setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_ContinueBtnMouseClicked

    private void askSave(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_askSave
        // TODO add your handling code here:
        if(javax.swing.JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit without saving\n(to exit and save"
                + " press the \"Done\" button)") == 0){
            this.dispose();
        }
    }//GEN-LAST:event_askSave

    private String inputCheck(){
        // TODO: do check here and return what needs to be fixed, if the return is "" then no errors
        // one check one could do is to check if the dishInfo number of lines is divisible by three
        // dishInfo;
        // dishType;
        return "";
    }
    
    private String getFileName(){
        return folderName + "/" + restInfo.getRestaurantName() + "." + fileExtensionName;
    }
    
    private void addDishInfo(DishInfo dish){
        Dish temp;
        try{
        String[] dishes = dishInfo.getText().split("\n\n");
        System.out.println("split into " + dishes.length);
        for(int i = 0; i < dishes.length; i += 3){
            temp = new Dish(dishes[i], dishes[i+1], dishes[i+2]);
            dish.addDish(temp);
        }
        } catch(Exception ex){
            System.out.println("invalid input");
        }
    }
    
    private void writeDishInfosToFile(PrintWriter outFile){
        Iterator<DishInfo> iterator = restInfo.getIteratorDishes();
        
        while(iterator.hasNext()){
            DishInfo dishInfoI = iterator.next();
            outFile.println(dishTypePre + dishInfoI.getDishType());
            Iterator<Dish> i = dishInfoI.getIterator();
            while(i.hasNext()){
                Dish dish = i.next();
                outFile.println(dishNamepre + dish.getDishName());
                outFile.println(dishDescriptionPre + dish.getDishDescription());
                outFile.println(dishPricePre + dish.getDishPrice());
                outFile.println();
            }
            outFile.println();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DishGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DishGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DishGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DishGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DishGUI(new RestaurantInfo("restaurant", "location")).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContinueBtn;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JTextArea dishInfo;
    private javax.swing.JTextField dishType;
    private javax.swing.JButton doneBtn;
    private javax.swing.JLabel enterDishInfo;
    private javax.swing.JLabel enterDishType;
    private javax.swing.JTextArea exampleDishInfo;
    private javax.swing.JScrollPane exampleScrPn;
    private javax.swing.JScrollPane infoScrPn;
    private javax.swing.JLabel inputError;
    private javax.swing.JLabel titel;
    // End of variables declaration//GEN-END:variables
}
