/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package infocollector;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JComboBox;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Mattis Skulle kunna göra så att jag har en hashmap med alla länen och
 * när man väljer ett län så returneras alla städerna i det länet och då kommer
 * dem upp i comboboxen.
 *
 * för att sätta ett standard val på comboboxen skriv
 * locationCBox.setSelectedIndex(index);
 *
 */
public class RestaurantGUI extends javax.swing.JFrame{

    private int preferedIndex = 0;
    private ArrayList<LanLocation> lanLocations;

    /**
     * Creates new form RestaurantGUI
     */
    public RestaurantGUI() {
        lanLocations = new ArrayList<LanLocation>();
        initializeCBox();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerLbl = new javax.swing.JLabel();
        restaurantNameLbl = new javax.swing.JLabel();
        restaurantLocationLbl = new javax.swing.JLabel();
        restaurantNameField = new javax.swing.JTextField();
        lanLocationCBox = new javax.swing.JComboBox();
        restaurantCityLbl = new javax.swing.JLabel();
        cityLocationCBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headerLbl.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        headerLbl.setText("Restaurant");

        restaurantNameLbl.setText("restaurant name:");

        restaurantLocationLbl.setText("restaurant län:");

        lanLocationCBox.setModel(cityLocationCBox.getModel());

        restaurantCityLbl.setText("restaurant city:");

        cityLocationCBox.setModel(lanLocationCBox.getModel());

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnClicked(evt);
            }
        });

        initializeCBox();

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(restaurantNameLbl)
                            .addComponent(restaurantLocationLbl)
                            .addComponent(restaurantCityLbl))
                        .addGap(27, 27, 27)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityLocationCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lanLocationCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headerLbl)
                            .addComponent(restaurantNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLbl)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantNameLbl)
                    .addComponent(restaurantNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantLocationLbl)
                    .addComponent(lanLocationCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantCityLbl)
                    .addComponent(cityLocationCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnClicked
        // TODO add your handling code here:
        // create an RestaurantInfo and then create a new DishGUI with it
        String lanLocation;
        String cityLocation;
        String restaurantName;

        lanLocation = (String) lanLocationCBox.getSelectedItem();
        cityLocation = (String) cityLocationCBox.getSelectedItem();
        restaurantName = restaurantNameField.getText();

        RestaurantInfo restInfo = new RestaurantInfo(restaurantName, (lanLocation + "   " + cityLocation));

        new DishGUI(restInfo).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_okBtnClicked

    private void initializeCBox() {
        // TODO: read from city file and enter the values into the lanLocations
        lanLocationCBox = new JComboBox(new Object[]{"län1", "län2"});
        cityLocationCBox = new JComboBox(new Object[]{"stad1", "stad2"});
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RestaurantGUI().setVisible(true);
            }
        });
    }

    private class LanLocation {

        private String lanLocation;
        private ArrayList<String> cities; // the String is the name of the city

        public LanLocation() {
            cities = new ArrayList<String>();
        }

        public void addCity(String city) {
            cities.add(city);
        }

        public String[] getCities() {
            String[] citiesStrings = new String[cities.size()];
            int tempIndex = 0;
            Iterator<String> i = cities.iterator();
            while (i.hasNext()) {
                citiesStrings[tempIndex++] = i.next();
            }
            return citiesStrings;
        }

        public String getLanLocation() {
            return lanLocation;
        }

        public void setLanLocation(String lanLocation) {
            this.lanLocation = lanLocation;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cityLocationCBox;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox lanLocationCBox;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel restaurantCityLbl;
    private javax.swing.JLabel restaurantLocationLbl;
    private javax.swing.JTextField restaurantNameField;
    private javax.swing.JLabel restaurantNameLbl;
    // End of variables declaration//GEN-END:variables
}
